const express=require("express")
const app=express() 
const port=3000
const db=require('./models')
const user_router=require("./routers/user-routes")
const norme_router=require("./routers/norme-routes")
const chapitre_router=require("./routers/chapitre-routes")
const article_router=require("./routers/article-routes")
const question_router=require("./routers/question-routes")
const projet_router=require("./routers/projet-routes")

app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use('/',user_router)
app.use('/',norme_router)
app.use('/',chapitre_router)
app.use('/',article_router)
app.use('/',question_router)
app.use('/',projet_router)
// app.get('/', (req,res)=>{
//     res.send('hello World')
// })
db.sequelize.sync().then(()=>{
    app.listen(port, ()=>console.log(`Server running on port ${port}`))
})
